name: Build and publish Docker image

on:
  # push:
  #   branches:
  #   - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # user/reponame


jobs:
  publish:
    runs-on: ubuntu-latest

    # Set permissions for GitHub token
    # <https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#authenticating-to-package-registries-on-github>
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8  # v2.0.0

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6  # v2.0.0

    - name: Prepare metadata for nsd
      id: meta_nsd
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a  # v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,enable=true,prefix=nsd-git-
          type=raw,value=nsd-latest

    - name: Prepare metadata for modeegdriver
      id: meta_modeegdriver
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a  # v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,enable=true,prefix=modeegdriver-git-
          type=raw,value=modeegdriver-latest

    - name: Prepare metadata for plot
      id: meta_plot
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a  # v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,enable=true,prefix=plot-git-
          type=raw,value=plot-latest

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b  # v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push nsd Docker image
      id: docker_build_nsd
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8  # v3.0.0
      with:
        context: ./
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_nsd.outputs.tags }}
        labels: ${{ steps.meta_nsd.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nsd-latest
        cache-to: type=inline
        target: nsd-target

    - name: Build and push modeegdriver Docker image
      id: docker_build_modeegdriver
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8  # v3.0.0
      with:
        context: ./
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_modeegdriver.outputs.tags }}
        labels: ${{ steps.meta_modeegdriver.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:modeegdriver-latest
        cache-to: type=inline
        target: modeegdriver-target

    - name: Build and push plot Docker image
      id: docker_build_plot
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8  # v3.0.0
      with:
        context: ./
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta_plot.outputs.tags }}
        labels: ${{ steps.meta_plot.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:plot-latest
        cache-to: type=inline
        target: plot-target
